// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetLang():Promise<string>;

export function GetSaveDir():Promise<string>;

export function GetServerInfo():Promise<Record<string, any>>;

export function GetUploadHistory():Promise<Array<main.UploadRecord>>;

export function SelectSaveDir():Promise<string>;

export function SetLang(arg1:string):Promise<void>;
