// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCompressSettings() {
  return window['go']['main']['App']['GetCompressSettings']();
}

export function GetLang() {
  return window['go']['main']['App']['GetLang']();
}

export function GetSaveDir() {
  return window['go']['main']['App']['GetSaveDir']();
}

export function GetServerInfo() {
  return window['go']['main']['App']['GetServerInfo']();
}

export function GetUploadHistory() {
  return window['go']['main']['App']['GetUploadHistory']();
}

export function SelectSaveDir() {
  return window['go']['main']['App']['SelectSaveDir']();
}

export function SetCompressSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCompressSettings'](arg1, arg2, arg3);
}

export function SetLang(arg1) {
  return window['go']['main']['App']['SetLang'](arg1);
}
